### ISSUE TITLE
Yarn build fails

### ISSUE THREAD

**Issue by uchenoel** [pinterest/gestalt#722]
i am using node v8.0.0, yarn v1.22.0, npm  v5.0.0

but when i am in the packages/gestalt folder and i run yarn build it fails with this error
```bash 
$ yarn build
yarn run v1.22.0
$ rollup -c rollup.config.js
[!] SyntaxError: Unexpected token ...
C:\Users\abram\desktop\gestalt\packages\gestalt\node_modules\boxen\index.js:26
                        ...detail
                        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\abram\D
esktop\gestalt\packages\gestalt\node_modules\rollup\dist\bin\rollup:827:17)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
```

**Comment by christianvuerings** [comment]
Related to #712

**Comment by dangerismycat** [comment]
Closing this for lack of activity for almost a year. If this is still an issue for you, please feel free to re-open.

**Comment by alison777** [comment]
> estoy usando el nodo v8.0.0, hilo v1.22.0, npm v5.0.0
> 
> pero cuando estoy en la carpeta packages/gestalt y ejecuto la compilación de hilo falla con este error
> 
> ```shell
> $ yarn build
> yarn run v1.22.0
> $ rollup -c rollup.config.js
> [!] SyntaxError: Unexpected token ...
> C:\Users\abram\desktop\gestalt\packages\gestalt\node_modules\boxen\index.js:26
>                         ...detail
>                         ^^^
> 
> SyntaxError: Unexpected token ...
>     at createScript (vm.js:74:10)
>     at Object.runInThisContext (vm.js:116:10)
>     at Module._compile (module.js:533:28)
>     at Module._extensions..js (module.js:580:10)
>     at Object.require.extensions.(anonymous function) [as .js] (C:\Users\abram\D
> esktop\gestalt\packages\gestalt\node_modules\rollup\dist\bin\rollup:827:17)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
> and.
> ```

Hello!! I have the same error, how did you solve it??

**Comment by alison777** [comment]
> i am using node v8.0.0, yarn v1.22.0, npm v5.0.0
> 
> but when i am in the packages/gestalt folder and i run yarn build it fails with this error
> 
> ```shell
> $ yarn build
> yarn run v1.22.0
> $ rollup -c rollup.config.js
> [!] SyntaxError: Unexpected token ...
> C:\Users\abram\desktop\gestalt\packages\gestalt\node_modules\boxen\index.js:26
>                         ...detail
>                         ^^^
> 
> SyntaxError: Unexpected token ...
>     at createScript (vm.js:74:10)
>     at Object.runInThisContext (vm.js:116:10)
>     at Module._compile (module.js:533:28)
>     at Module._extensions..js (module.js:580:10)
>     at Object.require.extensions.(anonymous function) [as .js] (C:\Users\abram\D
> esktop\gestalt\packages\gestalt\node_modules\rollup\dist\bin\rollup:827:17)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
> and.
> ```

Hello!! I have the same error, how did you solve it?
